# Generated by Django 4.2.1 on 2023-05-09 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpMst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.IntegerField()),
                ('ename', models.CharField(max_length=100)),
                ('orgid', models.IntegerField()),
                ('jdate', models.DateField()),
                ('bdate', models.DateField()),
                ('tdate', models.DateField()),
                ('edept', models.IntegerField()),
            ],
        ),
    ]
