# Generated by Django 4.2.1 on 2023-05-09 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0002_empmst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empmst',
            name='edept',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='empmst',
            name='orgid',
            field=models.IntegerField(default=0),
        ),
    ]
